Chinese-Code-Resources/ytenx/ytenx/kyonh/urls.py
# coding=utf-8
import ytenx.kyonh.views
from django.conf.urls import url

urlpatterns = [
  url(r'^intro$', ytenx.kyonh.views.intro_page),
  url(r'^sieux$', ytenx.kyonh.views.sieux_yonh_list_page, name='kyonh-sieux_yonh_list_page'),
  url(r'^sieux/(\d{1,4})/$', ytenx.kyonh.views.sieux_yonh_page, name='kyonh-sieux_yonh_page'),
  url(r'^dzih$', ytenx.kyonh.views.dzih_pieux, name='kyonh-dzih_pieux'),
  url(r'^dzih/(\d{1,5})/$', ytenx.kyonh.views.dzih, name='kyonh-dzih'),
  url(r'^cjeng$', ytenx.kyonh.views.cjeng_mux_list_page, name='kyonh-cjeng_mux_list_page'),
  url(r'^cjeng/(.+)/$', ytenx.kyonh.views.cjeng_mux_page, name='kyonh-cjeng_mux_page'),
  url(r'^yonh$', ytenx.kyonh.views.yonh_mux_list_page, name='kyonh-yonh_mux_list_page'),
  url(r'^yonh/(.+)/$', ytenx.kyonh.views.yonh_mux_page, name='kyonh-yonh_mux_page'),
  url(r'^yonhmiuk$', ytenx.kyonh.views.yonh_miuk_list_page, name='kyonh-yonh_miuk_list_page'),
  url(r'^yonhmiuk/(.+)/$', ytenx.kyonh.views.yonh_miuk_page, name='kyonh-yonh_miuk_page'),
  url(r'^cjengngix$', ytenx.kyonh.views.cjeng_ngix_list_page, name='kyonh-cjeng_ngix_list_page'),
  url(r'^yonhngix$', ytenx.kyonh.views.yonh_ngix_list_page, name='kyonh-yonh_ngix_list_page'),
  url(r'^yonhdo$', ytenx.kyonh.views.yonh_do_page, name='kyonh-yonh_do_page'),
  url(r'^cio/(\d{1,1})/(\d{1,3})/$', ytenx.kyonh.views.cio_page, name='kyonh-cio_page'),
  url(r'^pyanx/dciangx/(.+)/$', ytenx.kyonh.views.pyanx_dciangx_page, name='kyonh-pyanx_dciangx_page'),
  url(r'^pyanx/ghrax/(.+)/$', ytenx.kyonh.views.pyanx_ghrax_page, name='kyonh-pyanx_ghrax_page'),
  url(r'^$', ytenx.kyonh.views.index_page, name='kyonh'),
]

Chinese-Code-Resources/ytenx/ytenx/pyonh/urls.py
# coding=utf-8
import ytenx.pyonh.views
from django.conf.urls import url

urlpatterns = [
  url(r'^$', ytenx.pyonh.views.pyon_yonh, name='pyon_yonh'),
  url(r'^sieux$', ytenx.pyonh.views.sieux_yonh_pieux, name='pyon_yonh-sieux_yonh_pieux'),
  url(r'^sieux/(\d{1,4})/$', ytenx.pyonh.views.sieux_yonh, name='pyon_yonh-sieux_yonh'),
  url(r'^dzih$', ytenx.pyonh.views.dzih_pieux, name='pyon_yonh-dzih_pieux'),
  url(r'^dzih/(\d{1,4})/$', ytenx.pyonh.views.dzih, name='pyon_yonh-dzih'),
  url(r'^cjeng$', ytenx.pyonh.views.cjeng_mux_pieux, name='pyon_yonh-cjeng_mux_pieux'),
  url(r'^cjeng/(.+)/$', ytenx.pyonh.views.cjeng_mux, name='pyon_yonh-cjeng_mux'),
  url(r'^yonh$', ytenx.pyonh.views.yonh_mux_pieux, name='pyon_yonh-yonh_mux_pieux'),
  url(r'^yonh/(.+)/$', ytenx.pyonh.views.yonh_mux, name='pyon_yonh-yonh_mux'),
  url(r'^cio/(\d{1,1})/(\d{1,3})/$', ytenx.pyonh.views.cio, name='pyon_yonh-cio'),
]

Chinese-Code-Resources/ytenx/ytenx/trngyan/urls.py
# coding=utf-8
import ytenx.trngyan.views
from django.conf.urls import url

urlpatterns = [
  url(r'^$', ytenx.trngyan.views.triung_ngyan_qim_yonh, name='triung_ngyan_qim_yonh'),
  url(r'^sieux/$', ytenx.trngyan.views.sieux_yonh_pieux, name='trngyan-sieux_yonh_pieux'),
  url(r'^sieux/(\d{1,4})/$', ytenx.trngyan.views.sieux_yonh, name='trngyan-sieux_yonh'),
  url(r'^dzih/$', ytenx.trngyan.views.dzih_pieux, name='trngyan-dzih_pieux'),
  url(r'^dzih/(.+)/$', ytenx.trngyan.views.dzih, name='trngyan-dzih'),
  url(r'^cjeng/$', ytenx.trngyan.views.cjeng_mux_pieux, name='trngyan-cjeng_mux_pieux'),
  url(r'^cjeng/(.+)/$', ytenx.trngyan.views.cjeng_mux, name='trngyan-cjeng_mux'),
  url(r'^yonh/$', ytenx.trngyan.views.yonh_mux_pieux, name='trngyan-yonh_mux_pieux'),
  url(r'^yonh/(.+)/$', ytenx.trngyan.views.yonh_mux, name='trngyan-yonh_mux'),
  url(r'^cio/(\d{1,1})/(\d{1,3})/$', ytenx.trngyan.views.cio, name='trngyan-cio'),
]

Chinese-Code-Resources/ytenx/ytenx/urls.py
# coding=utf-8
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from ytenx.views import index_page, renew_session, about_page, zim, kiemx_sriek

urlpatterns = [
  url(r'^kyonh/', include('ytenx.kyonh.urls')),
  url(r'^tcyts/', include('ytenx.tcenghyonhtsen.urls')),
  url(r'^pyonh/', include('ytenx.pyonh.urls')),
  url(r'^trngyan/', include('ytenx.trngyan.urls')),
  url(r'^dciangx/', include('ytenx.dciangxkox.urls')),
  url(r'^byohlyuk/', include('ytenx.byohlyuk.urls')),
  url(r'^$', index_page, name='index_page'),
  url(r'^r$', renew_session, name='renew_session'),
  url(r'^about$', about_page, name='about_page'),
  url(r'^zim$', zim, name='zim'),
  url(r'^sriek$', kiemx_sriek, name='kiemx_sriek'),
]

urlpatterns += staticfiles_urlpatterns()

Chinese-Code-Resources/ytenx/ytenx/jihthex/models.py
# coding=utf-8
from django.db import models

#書葉
class Dzih(models.Model):
  #字
  dzih = models.CharField(primary_key=True, max_length=1)
  #全等異體
  dzyen_tongx = models.ManyToManyField('Dzih', related_name='dzyen_tongx_pyanx')
  #語義交疊異體
  krau_dep = models.ManyToManyField('Dzih', related_name='krau_dep_pyanx')
  #簡體
  krenx = models.ManyToManyField('Dzih', related_name='krenx_pyanx')
  #繁體
  byan = models.ManyToManyField('Dzih', related_name='byan_pyanx')
  #Unihan所未收錄者
  tha = models.ManyToManyField('Dzih', related_name='tha_pyanx')

  def __str__(self):
    return self.dzih

Chinese-Code-Resources/ytenx/ytenx/byohlyuk/views.py
# coding=utf-8
from django.http import Http404
from django.shortcuts import render
from django.core.paginator import InvalidPage, EmptyPage
from ytenx.helpers.paginator import Paginator

def byoh_lyuk(request, name):
  if name == 'KienxPyan':
    return kienx_pyan(request)

  if not name:
    name = 'miuk_lyuk'
  
  path = 'byohlyuk/' + name + '.html'
  try:
    return render(request, path)
  except:
    raise Http404()

def kienx_pyan(request):
  import os
  pwd = os.path.dirname(__file__)

  kienx_pyan_pieux = []
  for line in open(pwd + '/st_multi.txt'):
    line = line[:-1]
    line = line.split('\t')
    kienx_pyan_pieux.append(line)

  return render(request, 'byohlyuk/KienxPyan.html', {
    'kienx_pyan_pieux': kienx_pyan_pieux,
  })

Chinese-Code-Resources/ytenx/ytenx/dciangxkox/views.py
# coding=utf-8
from django.http import Http404
from django.shortcuts import render
from django.views.decorators.cache import cache_page
from django.db.models import Q
from ytenx.helpers.paginator import Paginator
from django.core.paginator import InvalidPage, EmptyPage
from ytenx.dciangxkox.models import Dzih, CjengByo, YonhBox

def dciangx_kox(request):
  return render(request, 'dciangxkox/dciangx_kox.html')

def dzih(request, id):
  try:
    dzih = Dzih.objects.get(id = id)
  except:
    raise Http404()

  return render(request, 'dciangxkox/dzih.html', {
    'dzih': dzih,
  })

def dzih_pieux(request):
  yonh = request.GET.get('yonh')
  
  query = Q()
  if yonh:
    query &= Q(yonh = YonhBox.objects.get(mjeng = yonh))
  
  dzih_pieux = Dzih.objects.filter(query).order_by('ziox')
  paginator = Paginator(dzih_pieux, 15)
  try:
    dzih_pieux = paginator.page(request.GET)
  except (EmptyPage, InvalidPage):
    raise Http404()
  
  dzih_pieux.yonh = yonh
  
  cjeng_pieux = CjengByo.objects.all()
  yonh_pieux = YonhBox.objects.all()
  
  return render(request, 'dciangxkox/dzih_pieux.html', {
    'dzih_pieux': dzih_pieux,
    'cjeng_pieux': cjeng_pieux,
    'yonh_pieux': yonh_pieux,
  })

@cache_page(60 * 60 * 24)
def cjeng_byo_pieux(request):
  cjeng_pieux = CjengByo.objects.all()
  paginator = Paginator(cjeng_pieux, 15)
  try:
    cjeng_pieux = paginator.page(request.GET)
  except (EmptyPage, InvalidPage):
    raise Http404()
  
  return render(request, 'dciangxkox/cjeng_byo_pieux.html', {
    'cjeng_pieux': cjeng_pieux,
  })

@cache_page(60 * 60 * 24)
def cjeng_byo(request, mjeng):
  try:
    cjeng = CjengByo.objects.get(mjeng = mjeng)
  except:
    raise Http404()

  return render(request, 'dciangxkox/cjeng_byo.html', {
    'cjeng': cjeng,
  })

@cache_page(60 * 60 * 24)
def yonh_box_pieux(request):
  return render(request, 'dciangxkox/yonh_box_pieux.html', {
    'yonh_pieux': YonhBox.objects.all(),
  })

@cache_page(60 * 60 * 24)
def yonh_box(request, mjeng):
  try:
    yonh = YonhBox.objects.get(mjeng = mjeng)
  except:
    raise Http404()

  return render(request, 'dciangxkox/yonh_box.html', {
    'yonh': yonh,
  })

Chinese-Code-Resources/ytenx/ytenx/kyonh/views.py
# coding=utf-8
from django.http import Http404
from django.shortcuts import render
from django.views.decorators.cache import cache_page
from django.db.models import Q
from ytenx.helpers.paginator import Paginator
from django.core.paginator import InvalidPage, EmptyPage
from ytenx.kyonh.models import SieuxYonh, CjengMux, YonhMux, CjengLyih, DrakDzuonDang, YonhMiuk, YonhMiukDzip, DciangxDzih, GhraxDzih, Dzih, YonhCjep, YonhGheh

def index_page(request):
  return render(request, 'kyonh/index.html')

def intro_page(request):
  return render(request, 'kyonh/intro.html')

def sieux_yonh_page(request, ziox):
  try:
    sieux_yonh = SieuxYonh.objects.get(ziox=ziox)
  except:
    raise Http404()

  return render(request, 'kyonh/sieux_yonh.html', {
    'sieux_yonh': sieux_yonh,
  })

def sieux_yonh_list_page(request):
  cjeng = request.GET.get('cjeng')
  yonh = request.GET.get('yonh')
  deuh = request.GET.get('deuh')
  tongx = request.GET.get('tongx')
  ho = request.GET.get('ho')
  
  query = Q()
  if cjeng:
    query &= Q(cjeng__in = CjengMux.objects.filter(dzih=cjeng))
  if yonh:
    query &= Q(yonhMiuk__in = YonhMiuk.objects.filter(
      gheh__in = YonhGheh.objects.filter(dzih=yonh)
    ))
  if deuh:
    query &= Q(yonhMiuk__in = YonhMiuk.objects.filter(
      deuh = int(deuh)
    ))
  if tongx:
    query &= Q(yonh__in = YonhMux.objects.filter(
      tongx = int(tongx)
    ))
  if ho:
    query &= Q(yonh__in = YonhMux.objects.filter(
      ho = int(ho)
    ))
  
  sieux_yonh_pieux = SieuxYonh.objects.filter(query).order_by('ziox')
  paginator = Paginator(sieux_yonh_pieux, 15)
  try:
    sieux_yonh_pieux = paginator.page(request.GET)
  except (EmptyPage, InvalidPage):
    raise Http404()
  
  cjeng_pieux = []
  for lyih in CjengLyih.objects.all().order_by('ziox'):
    cjeng_pieux.append(lyih)
    cjeng_pieux += lyih.cjengmux_set.all()
  
  yonh_pieux = []
  for cjep in YonhCjep.objects.all():
    yonh_pieux.append(cjep)
    yonh_pieux += cjep.yonhgheh_set.all()
  
  return render(request, 'kyonh/sieux_yonh_pieux.html', {
    'sieux_yonh_pieux': sieux_yonh_pieux,
    'cjeng_pieux': cjeng_pieux,
    'yonh_pieux': yonh_pieux,
    'p_cjeng': cjeng,
    'p_yonh': yonh,
    'p_deuh': deuh,
    'p_tongx': tongx,
    'p_ho': ho,
  })

def dzih(request, ziox):
  try:
    dzih = Dzih.objects.get(ziox=ziox)
  except:
    raise Http404()

  return render(request, 'kyonh/dzih.html', {
    'dzih': dzih,
  })

def dzih_pieux(request):
  dzih_pieux = Dzih.objects.all()
  paginator = Paginator(dzih_pieux, 15)
  try:
    dzih_pieux = paginator.page(request.GET)
  except (EmptyPage, InvalidPage):
    raise Http404()
  return render(request, 'kyonh/dzih_pieux.html', {
    'dzih_pieux': dzih_pieux,
  })

@cache_page(60 * 60 * 24)
def cjeng_mux_list_page(request):
  return render(request, 'kyonh/cjeng_mux_list.html', {
    'cjeng_mux_list': CjengMux.objects.all(),
  })

@cache_page(60 * 60 * 24)
def yonh_mux_list_page(request):
  return render(request, 'kyonh/yonh_mux_list.html', {
    'yonh_mux_list': YonhMux.objects.get_pairs(),
  })

@cache_page(60 * 60 * 24)
def yonh_miuk_list_page(request):
  return render(request, 'kyonh/yonh_miuk_list.html', {
    'yonh_miuk_list': YonhMiukDzip.objects.all(),
  })

@cache_page(60 * 60 * 24)
def cjeng_ngix_list_page(request):
  return render(request, 'kyonh/cjeng_ngix_list.html', {
    'cjeng_mux_list': CjengMux.objects.all(),
  })

@cache_page(60 * 60 * 24)
def yonh_ngix_list_page(request):
  return render(request, 'kyonh/yonh_ngix_list.html', {
    'yonh_mux_list': YonhMux.objects.get_pairs(),
  })

@cache_page(60 * 60 * 24)
def yonh_do_page(request):
  paginator = Paginator(YonhMiukDzip.objects.all(), 1)
  try:
    dzip_list = paginator.page(request.GET)
  except (EmptyPage, InvalidPage):
    raise Http404()

  dzip = dzip_list[0]
  yonh_do = SieuxYonh.objects.get_yonh_do(dzip)

  return render(request, 'kyonh/yonh_do.html', {
    'yonh_do': yonh_do,
    'cjeng_lyih_list': CjengLyih.objects.all().order_by('ziox'),
    'dzip': dzip,
    'dzip_list': dzip_list,
  })

def cio_page(request, kyenh, jep):
  cio = DrakDzuonDang.objects.get(
    kyenh = kyenh,
    jep = jep,
  )
  
  return render(request, 'kyonh/cio.html', {
    'cio': cio,
  })

def cjeng_mux_page(request, dzih):
  try:
    cjeng = CjengMux.objects.get(dzih = dzih)
  except:
    raise Http404()

  return render(request, 'kyonh/cjeng_mux.html', {
    'cjeng': cjeng,
  })

def yonh_mux_page(request, mjeng):
  try:
    yonh = YonhMux.objects.get(mjeng = mjeng)
  except:
    raise Http404()

  return render(request, 'kyonh/yonh_mux.html', {
    'yonh': yonh,
  })

def yonh_miuk_page(request, dzih):
  try:
    yonh_miuk = YonhMiuk.objects.get(dzih = dzih)
  except:
    raise Http404()

  return render(request, 'kyonh/yonh_miuk.html', {
    'yonh_miuk': yonh_miuk,
  })

def pyanx_dciangx_page(request, dzih):
  try:
    dciangx = DciangxDzih.objects.get(dzih = dzih)
  except:
    raise Http404()

  return render(request, 'kyonh/pyanx_dciangx.html', {
    'dciangx': dciangx,
  })

def pyanx_ghrax_page(request, dzih):
  try:
    ghrax = GhraxDzih.objects.get(dzih = dzih)
  except:
    raise Http404()

  return render(request, 'kyonh/pyanx_ghrax.html', {
    'ghrax': ghrax,
  })

Chinese-Code-Resources/ytenx/ytenx/pyonh/views.py
# coding=utf-8
from django.http import Http404
from django.shortcuts import render
from django.views.decorators.cache import cache_page
from django.db.models import Q
from ytenx.helpers.paginator import Paginator
from django.core.paginator import InvalidPage, EmptyPage
from ytenx.pyonh.models import CjengLyih, CjengMux, YonhBox, Dzih, SieuxYonh, Cio, YonhMux

def pyon_yonh(request):
  return render(request, 'pyonh/pyon_yonh.html', {
    'cjeng_mux_pieux': CjengLyih.objects.all(),
    'yonh_mux_pieux': YonhBox.objects.all(),
  })

def sieux_yonh(request, ziox):
  try:
    sieux_yonh = SieuxYonh.objects.get(ziox = ziox)
  except:
    raise Http404()

  return render(request, 'pyonh/sieux_yonh.html', {
    'sieux_yonh': sieux_yonh,
  })

def sieux_yonh_pieux(request):
  cjeng = request.GET.get('cjeng')
  yonh = request.GET.get('yonh')
  qim_jang = request.GET.get('qim_jang')
  deuh = request.GET.get('deuh')
  
  query = Q()
  if cjeng:
    query &= Q(cjeng = CjengMux.objects.get(dzih = cjeng))
  if yonh:
    query &= Q(yonh_box = YonhBox.objects.get(mjeng = yonh))
  if deuh:
    query &= Q(deuh = deuh)
  if qim_jang:
    query &= Q(qim_jang = qim_jang)
  
  sieux_yonh_pieux = SieuxYonh.objects.filter(query).order_by('ziox')
  paginator = Paginator(sieux_yonh_pieux, 15)
  try:
    sieux_yonh_pieux = paginator.page(request.GET)
  except (EmptyPage, InvalidPage):
    raise Http404()
  
  sieux_yonh_pieux.cjeng = cjeng
  sieux_yonh_pieux.yonh = yonh
  sieux_yonh_pieux.deuh = deuh
  sieux_yonh_pieux.qim_jang = qim_jang
  
  cjeng_pieux = []
  for lyih in CjengLyih.objects.all():
    cjeng_pieux.append(lyih)
    cjeng_pieux += lyih.cjengmux_set.all()
  
  yonh_pieux = YonhBox.objects.all()
  
  return render(request, 'pyonh/sieux_yonh_pieux.html', {
    'sieux_yonh_pieux': sieux_yonh_pieux,
    'cjeng_pieux': cjeng_pieux,
    'yonh_pieux': yonh_pieux,
  })

def dzih(request, ziox):
  try:
    dzih = Dzih.objects.get(ziox=ziox)
  except:
    raise Http404()

  return render(request, 'pyonh/dzih.html', {
    'dzih': dzih,
  })

def dzih_pieux(request):
  dzih_pieux = Dzih.objects.all()
  paginator = Paginator(dzih_pieux, 15)
  try:
    dzih_pieux = paginator.page(request.GET)
  except (EmptyPage, InvalidPage):
    raise Http404()
  return render(request, 'pyonh/dzih_pieux.html', {
    'dzih_pieux': dzih_pieux,
  })

@cache_page(60 * 60 * 24)
def cjeng_mux_pieux(request):
  return render(request, 'pyonh/cjeng_mux_pieux.html', {
    'cjeng_mux_pieux': CjengLyih.objects.all(),
  })

@cache_page(60 * 60 * 24)
def cjeng_mux(request, dzih):
  try:
    cjeng = CjengMux.objects.get(dzih = dzih)
  except:
    raise Http404()

  return render(request, 'pyonh/cjeng_mux.html', {
    'cjeng': cjeng,
  })

@cache_page(60 * 60 * 24)
def yonh_mux_pieux(request):
  return render(request, 'pyonh/yonh_mux_pieux.html', {
    'yonh_mux_pieux': YonhBox.objects.all(),
  })

@cache_page(60 * 60 * 24)
def yonh_mux(request, mjeng):
  try:
    yonh = YonhMux.objects.get(mjeng = mjeng)
  except:
    raise Http404()

  return render(request, 'pyonh/yonh_mux.html', {
    'yonh': yonh,
  })

def cio(request, kyenh, jep):
  cio = Cio.objects.get(
    kyenh = kyenh,
    jep = jep,
  )
  
  return render(request, 'pyonh/cio.html', {
    'cio': cio,
  })

Chinese-Code-Resources/ytenx/ytenx/templates/dciangxkox/cio.html
{% extends "trngyan/poh.html" %}
{% load ytenx %}
{% block trngyan_cio_active %}active{% endblock %}
{% block title %}第{{cio.kyenh|sryoh}}卷第{{cio.jep|sryoh}}䈎 - 中原音韻{% endblock %}
{% block content %}
<div class="page-header">
  <h1>第{{cio.jep|sryoh}}䈎 <small>《欽定四庫全書・集部・中原音韻・{{cio.kyenh|dciangx_ghrax}}卷》</small></h1>
</div>
{% include "pohpyon/navibar.html" with urls=cio.urls only %}
<div class="span10">
  {% if cio.sieuxyonh_set.all %}
    <div class="row">
      <h2>小韻</h2>
      {% for sieux in cio.sieux_yonh %}
        <a href="{% url 'trngyan-sieux_yonh' sieux.ziox %}">{{sieux}}</a>
      {% endfor %}
    </div>
  {% endif %}
  {% if cio.dzih_set.all %}
    <div class="row">
      <h2>字頭</h2>
      {% for dzih in cio.dzih %}
        <a href="{% url 'trngyan-dzih' dzih.id %}">{{dzih}}</a>
      {% endfor %}
    </div>
  {% endif %}
  <div class="row">
    <h2>圖片</h2>
    <div class="thumbnail">
      <a href="/static/img/TriungNgyanQimYonh/Kyenh{{cio.kyenh}}/{{cio.jep}}.gif">
        <img src="/static/img/TriungNgyanQimYonh/Kyenh{{cio.kyenh}}/{{cio.jep}}.gif" alt="" >
      </a>
    </div>
  </div>
</div>
{% endblock %}

Chinese-Code-Resources/ytenx/ytenx/templates/dciangxkox/cjeng_byo.html
{% extends "dciangxkox/poh.html" %}
{% load ytenx %}
{% block dciangxkox_cjeng_active %}active{% endblock %}
{% block title %}{{cjeng}} - 聲符 - 上古音系{% endblock %}
{% block keywords %}{{cjeng}}, 聲符, 上古音系 {% endblock %}
{% block content %}
<div class="page-header">
  <h1>{{cjeng}} <small>上古音系聲符</small></h1>
</div>
<div class="span10">
  <div class="row">
    <h2>字</h2>
    {% for dzih in cjeng.dzih_set.all %}
      <a href="{% url 'dciangx_kox-dzih' dzih.id %}">{{dzih}}</a>
    {% endfor %}
  </div>
</div>
<div class="span10">
  <div class="row">
    <h2>韻部</h2>
    {% for yonh in cjeng.yonh_box %}
      <a href="{% url 'dciangx_kox-yonh_box' yonh.mjeng %}">{{yonh}}</a>
    {% endfor %}
  </div>
</div>
<div class="span10">
  <div class="row">
    <h2>擬音</h2>
    <ul class="horizontal-ltr">
    {% for ngix in cjeng.ngix %}
      <li>{{ngix}}</li>
    {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}

Chinese-Code-Resources/ytenx/ytenx/templates/dciangxkox/cjeng_byo_pieux.html
{% extends "dciangxkox/poh.html" %}
{% load ytenx %}
{% block dciangxkox_cjeng_active %}active{% endblock %}
{% block title %}聲符表 - 上古音系{% endblock %}
{% block keywords %}聲符, 上古音系, {% endblock %}
{% block content %}
<div class="page-header">
  <h1>聲符表 <small>上古音系</small></h1>
</div>
<div class="row tb-with-table-by-layout-direction">
  <div class="span10">
    <table class="table table-bordered table-condensed table-striped">
      <tr>
        <th>聲符</th>
        <th>字</th>
      </tr>
      {% for cjeng in cjeng_pieux %}
      <tr>
        <td>
    	  	<a href="{% url 'dciangx_kox-cjeng_byo' cjeng.mjeng %}">
    	  		{{cjeng}}
    	  	</a>
        </td>
        <td>
          {% for dzih in cjeng.dzih_set.all %}
            <a href="{% url 'dciangx_kox-dzih' dzih.id %}">{{dzih}}</a>
          {% endfor %}
        </td>
      </tr>
      {% endfor %}
    </table>
    {% include "pagination.html" with list=cjeng_pieux only %}
  </div>
</div>
{% endblock %}

Chinese-Code-Resources/ytenx/ytenx/templates/dciangxkox/yonh_box.html
{% extends "dciangxkox/poh.html" %}
{% load ytenx %}
{% block dciangxkox_yonh_active %}active{% endblock %}
{% block title %}{{yonh}} - 韻部 - 上古音系{% endblock %}
{% block keywords %}{{yonh}}, 韻部, 上古音系 {% endblock %}
{% block content %}
<div class="page-header">
  <h1>{{yonh}} <small>上古音系韻部</small></h1>
</div>
<div class="span10">
  <div class="row">
    <h2>字</h2>
    {% for dzih in yonh.dzih_set.all %}
      <a href="{% url 'dciangx_kox-dzih' dzih.id %}">{{dzih}}</a>
    {% endfor %}
  </div>
</div>
<div class="span10">
  <div class="row">
    <h2>聲符</h2>
    {% for cjeng in yonh.cjeng_byo %}
      <a href="{% url 'dciangx_kox-cjeng_byo' cjeng.mjeng %}">{{cjeng}}</a>
    {% endfor %}
  </div>
</div>
<div class="span10">
  <div class="row">
    <h2>擬音</h2>
    <ul class="horizontal-ltr">
    {% for ngix in yonh.ngix %}
      <li>{{ngix}}</li>
    {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}